# Generated by Django 3.0.5 on 2024-05-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0009_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.CharField(max_length=20, unique=True)),
                ('origin', models.CharField(max_length=40)),
                ('destination', models.CharField(max_length=40)),
                ('distance', models.PositiveIntegerField()),
                ('estimated_travel_time', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('make_model', models.CharField(max_length=40)),
                ('fuel_type', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('M', 'Under Maintenance')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='driver_license_number',
            field=models.CharField(default='N/A', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='employee_id',
            field=models.CharField(default='N/A', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='employment_status',
            field=models.CharField(choices=[('FT', 'Full Time'), ('PT', 'Part Time'), ('C', 'Contract')], default='FT', max_length=2),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(default='N/A', max_length=40),
        ),
    ]
